### ISSUE TITLE
Deleting Email object in onStatus() results in crash in Demo app

### ISSUE THREAD

**Issue by mmccullo** [kelvins/SMTPClient#1]
With Qt 5.10 for x64 2017 VS, deleting the _client email object in the onStatus() slot results in a crash.

Instead of "delete client_", use:

client_->deleteLater();

so the event loop can complete before client_ is deleted.

**Comment by kelvins** [comment]
Hello @mmccullo, it makes a lot of sense.

I changed the `delete client_;` to `client_->deleteLater();`.

The change was included in the following commit:

- [Use deleteLater to delete the client pointer (8bf73ef)](https://github.com/kelvins/SMTPClient/commit/8bf73ef88fb3713525062abd179a7168461b54fc)

Thanks a lot
